### ISSUE TITLE
有的文件可以被enum出来，但是exists显示不存在，也不能fopen

### ISSUE THREAD

**Issue by synodriver** [TheSnowfield/rucfs#2]

**Comment by synodriver** [comment]
已经确认[py封装](https://github.com/synodriver/pyrucfs)调用方法和test的一样的

**Comment by TheSnowfield** [comment]
![V@ 677J%(2C}1NG5LZ6@}J](https://user-images.githubusercontent.com/17957399/218165664-90e9817f-500b-448e-a9cf-7b3b99e33c36.png)
有沒有可能是mkfs.rucfs.py的問題

**Comment by synodriver** [comment]
快修罢）

**Comment by TheSnowfield** [comment]
> 快修罢）

修修修 我修

**Comment by TheSnowfield** [comment]
> 快修罢）

修好了 pls check (

**Comment by synodriver** [comment]
能通过测试了）
